name: "Update lotof.cloud.state"
description: "Updates the Docker image version in lotof.cloud.state"
inputs:
  repo-name:
    description: "Repository name"
    required: true
  commit-sha:
    description: "Commit SHA"
    required: true
  branch:
    description: "Branch"
    required: true
  ssh-key:
    description: "SSH private key"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup SSH key
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.ssh-key }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Checkout state repository
      shell: bash
      run: |
        GIT_SSH_COMMAND="ssh -i ~/.ssh/id_ed25519 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" \
        git clone --branch ${{ inputs.branch }} git@github.com:pieceowater-dev/lotof.cloud.state.git state-repo

    - name: Update image version
      shell: bash
      run: |
        cd ${{ inputs.repo-name }}
        sed -i "s|image:.*|image: ${GITHUB_REPOSITORY}:${{ inputs.commit-sha }}|" manifest.yaml
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add manifest.yaml
        git commit -m "Update image for ${{ inputs.repo-name }} to ${{ inputs.commit-sha }}"
        git push origin ${{ inputs.branch }}